// <auto-generated />
using System;
using BillTrackPro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BillTrackPro.Infrastructure.Migrations
{
    [DbContext(typeof(BillTrackDbContext))]
    [Migration("20260125160925_AddDefaultSchema")]
    partial class AddDefaultSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BillTrack")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BillTrackPro.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients", "BillTrack");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "https://i.pravatar.cc/150?u=1",
                            CompanyName = "Apex Logistics",
                            Email = "contact@apexlogistics.com",
                            IsActive = true,
                            Name = "Apex Logistics LLC"
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "https://i.pravatar.cc/150?u=2",
                            CompanyName = "Globex Corporation",
                            Email = "info@globex.com",
                            IsActive = true,
                            Name = "Globex Inc"
                        },
                        new
                        {
                            Id = 3,
                            AvatarUrl = "https://i.pravatar.cc/150?u=3",
                            CompanyName = "Soylent Corp",
                            Email = "sales@soylent.com",
                            IsActive = false,
                            Name = "Soylent Corp"
                        },
                        new
                        {
                            Id = 4,
                            AvatarUrl = "https://i.pravatar.cc/150?u=4",
                            CompanyName = "Initech Systems",
                            Email = "bill@initech.com",
                            IsActive = true,
                            Name = "Initech"
                        },
                        new
                        {
                            Id = 5,
                            AvatarUrl = "https://i.pravatar.cc/150?u=5",
                            CompanyName = "Umbrella Corp",
                            Email = "alice@umbrella.com",
                            IsActive = true,
                            Name = "Umbrella Corp"
                        },
                        new
                        {
                            Id = 6,
                            AvatarUrl = "https://i.pravatar.cc/150?u=6",
                            CompanyName = "Stark Industries",
                            Email = "tony@stark.com",
                            IsActive = true,
                            Name = "Stark Industries"
                        },
                        new
                        {
                            Id = 7,
                            AvatarUrl = "https://i.pravatar.cc/150?u=7",
                            CompanyName = "Cyberdyne",
                            Email = "skynet@cyberdyne.com",
                            IsActive = true,
                            Name = "Cyberdyne Systems"
                        },
                        new
                        {
                            Id = 8,
                            AvatarUrl = "https://i.pravatar.cc/150?u=8",
                            CompanyName = "Massive Dynamic",
                            Email = "nina@massive.com",
                            IsActive = true,
                            Name = "Massive Dynamic"
                        },
                        new
                        {
                            Id = 9,
                            AvatarUrl = "https://i.pravatar.cc/150?u=9",
                            CompanyName = "Hooli XYZ",
                            Email = "gavin@hooli.com",
                            IsActive = false,
                            Name = "Hooli"
                        },
                        new
                        {
                            Id = 10,
                            AvatarUrl = "https://i.pravatar.cc/150?u=10",
                            CompanyName = "Pied Piper",
                            Email = "richard@piedpiper.com",
                            IsActive = true,
                            Name = "Pied Piper"
                        },
                        new
                        {
                            Id = 11,
                            AvatarUrl = "https://i.pravatar.cc/150?u=11",
                            CompanyName = "Wayne Enterprises",
                            Email = "bruce@wayne.com",
                            IsActive = true,
                            Name = "Wayne Enterprises"
                        },
                        new
                        {
                            Id = 12,
                            AvatarUrl = "https://i.pravatar.cc/150?u=12",
                            CompanyName = "Acme Corp",
                            Email = "roadrunner@acme.com",
                            IsActive = true,
                            Name = "Acme Corp"
                        },
                        new
                        {
                            Id = 13,
                            AvatarUrl = "https://i.pravatar.cc/150?u=13",
                            CompanyName = "Oscorp Industries",
                            Email = "norman@oscorp.com",
                            IsActive = true,
                            Name = "Oscorp"
                        },
                        new
                        {
                            Id = 14,
                            AvatarUrl = "https://i.pravatar.cc/150?u=14",
                            CompanyName = "Nakatomi",
                            Email = "takagi@nakatomi.com",
                            IsActive = true,
                            Name = "Nakatomi Trading"
                        },
                        new
                        {
                            Id = 15,
                            AvatarUrl = "https://i.pravatar.cc/150?u=15",
                            CompanyName = "Tyrell Corporation",
                            Email = "elden@tyrell.com",
                            IsActive = false,
                            Name = "Tyrell Corp"
                        });
                });

            modelBuilder.Entity("BillTrackPro.Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateIssued")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Invoices", "BillTrack");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 12450.32m,
                            ClientId = 1,
                            DateIssued = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2026-001",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 3450.00m,
                            ClientId = 2,
                            DateIssued = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2026-002",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Amount = 8900.00m,
                            ClientId = 3,
                            DateIssued = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-003",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 2100.00m,
                            ClientId = 4,
                            DateIssued = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-004",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 5600.00m,
                            ClientId = 5,
                            DateIssued = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-005",
                            Status = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 15420.00m,
                            ClientId = 6,
                            DateIssued = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-006",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 4500.00m,
                            ClientId = 7,
                            DateIssued = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-007",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Amount = 7200.00m,
                            ClientId = 8,
                            DateIssued = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-008",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = 3750.00m,
                            ClientId = 1,
                            DateIssued = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-009",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            Amount = 9800.00m,
                            ClientId = 2,
                            DateIssued = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-010",
                            Status = 0
                        },
                        new
                        {
                            Id = 11,
                            Amount = 2450.00m,
                            ClientId = 9,
                            DateIssued = new DateTime(2025, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-011",
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            Amount = 16700.00m,
                            ClientId = 10,
                            DateIssued = new DateTime(2025, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-012",
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            Amount = 25000.00m,
                            ClientId = 11,
                            DateIssued = new DateTime(2025, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-013",
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            Amount = 6200.00m,
                            ClientId = 12,
                            DateIssued = new DateTime(2025, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-014",
                            Status = 0
                        },
                        new
                        {
                            Id = 15,
                            Amount = 8400.00m,
                            ClientId = 13,
                            DateIssued = new DateTime(2025, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-015",
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            Amount = 11900.00m,
                            ClientId = 14,
                            DateIssued = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-016",
                            Status = 1
                        },
                        new
                        {
                            Id = 17,
                            Amount = 1450.00m,
                            ClientId = 15,
                            DateIssued = new DateTime(2025, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-017",
                            Status = 2
                        },
                        new
                        {
                            Id = 18,
                            Amount = 4100.00m,
                            ClientId = 1,
                            DateIssued = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-018",
                            Status = 1
                        },
                        new
                        {
                            Id = 19,
                            Amount = 3300.00m,
                            ClientId = 3,
                            DateIssued = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-019",
                            Status = 1
                        },
                        new
                        {
                            Id = 20,
                            Amount = 7600.00m,
                            ClientId = 5,
                            DateIssued = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-020",
                            Status = 1
                        },
                        new
                        {
                            Id = 21,
                            Amount = 9200.00m,
                            ClientId = 6,
                            DateIssued = new DateTime(2025, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-021",
                            Status = 1
                        },
                        new
                        {
                            Id = 22,
                            Amount = 5500.00m,
                            ClientId = 8,
                            DateIssued = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-022",
                            Status = 0
                        },
                        new
                        {
                            Id = 23,
                            Amount = 12300.00m,
                            ClientId = 10,
                            DateIssued = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-023",
                            Status = 1
                        },
                        new
                        {
                            Id = 24,
                            Amount = 8800.00m,
                            ClientId = 11,
                            DateIssued = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2025-024",
                            Status = 1
                        });
                });

            modelBuilder.Entity("BillTrackPro.Domain.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyLogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles", "BillTrack");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "",
                            BrandColor = "#0F172A",
                            City = "San Francisco",
                            CompanyLogoUrl = "",
                            CompanyName = "TechFlow Solutions LLC",
                            Country = "United States",
                            Email = "alex@billcorp.com",
                            FullName = "Alex Morgan",
                            Phone = "+1 (555) 000-0000",
                            SecondaryColor = "#F59E0B",
                            StreetAddress = "450 Enterprise Blvd, Suite 200",
                            TaxId = "US-987654321",
                            Timezone = "Eastern Time (US & Canada) (GMT-05:00)",
                            Title = "Senior Product Manager",
                            ZipCode = "94105"
                        });
                });

            modelBuilder.Entity("BillTrackPro.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("BillTrackPro.Domain.Entities.Client", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BillTrackPro.Domain.Entities.Client", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
