// <auto-generated />
using System;
using BillTrackPro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BillTrackPro.Infrastructure.Migrations
{
    [DbContext(typeof(BillTrackDbContext))]
    [Migration("20260110172153_UpdateClientSchema")]
    partial class UpdateClientSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BillTrackPro.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "AL",
                            CompanyName = "Apex Logistics",
                            Email = "contact@apexlogistics.com",
                            IsActive = true,
                            Name = "Apex Logistics LLC"
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "GI",
                            CompanyName = "Globex Corporation",
                            Email = "info@globex.com",
                            IsActive = true,
                            Name = "Globex Inc"
                        },
                        new
                        {
                            Id = 3,
                            AvatarUrl = "SC",
                            CompanyName = "Soylent Corp",
                            Email = "sales@soylent.com",
                            IsActive = false,
                            Name = "Soylent Corp"
                        },
                        new
                        {
                            Id = 4,
                            AvatarUrl = "IT",
                            CompanyName = "Initech Systems",
                            Email = "bill@initech.com",
                            IsActive = true,
                            Name = "Initech"
                        });
                });

            modelBuilder.Entity("BillTrackPro.Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateIssued")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 12450.32m,
                            ClientId = 1,
                            DateIssued = new DateTime(2023, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-001",
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 3450.00m,
                            ClientId = 2,
                            DateIssued = new DateTime(2023, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-002",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 890.00m,
                            ClientId = 3,
                            DateIssued = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-003",
                            Status = "Overdue"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 2100.00m,
                            ClientId = 4,
                            DateIssued = new DateTime(2023, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-004",
                            Status = "Paid"
                        });
                });

            modelBuilder.Entity("BillTrackPro.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("BillTrackPro.Domain.Entities.Client", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BillTrackPro.Domain.Entities.Client", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
