// <auto-generated />
using System;
using BillTrackPro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BillTrackPro.Infrastructure.Migrations
{
    [DbContext(typeof(BillTrackDbContext))]
    partial class BillTrackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BillTrackPro.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "https://i.pravatar.cc/150?u=1",
                            CompanyName = "Apex Logistics",
                            Email = "contact@apexlogistics.com",
                            IsActive = true,
                            Name = "Apex Logistics LLC"
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "https://i.pravatar.cc/150?u=2",
                            CompanyName = "Globex Corporation",
                            Email = "info@globex.com",
                            IsActive = true,
                            Name = "Globex Inc"
                        },
                        new
                        {
                            Id = 3,
                            AvatarUrl = "https://i.pravatar.cc/150?u=3",
                            CompanyName = "Soylent Corp",
                            Email = "sales@soylent.com",
                            IsActive = false,
                            Name = "Soylent Corp"
                        },
                        new
                        {
                            Id = 4,
                            AvatarUrl = "https://i.pravatar.cc/150?u=4",
                            CompanyName = "Initech Systems",
                            Email = "bill@initech.com",
                            IsActive = true,
                            Name = "Initech"
                        },
                        new
                        {
                            Id = 5,
                            AvatarUrl = "https://i.pravatar.cc/150?u=5",
                            CompanyName = "Umbrella Corp",
                            Email = "alice@umbrella.com",
                            IsActive = true,
                            Name = "Umbrella Corp"
                        },
                        new
                        {
                            Id = 6,
                            AvatarUrl = "https://i.pravatar.cc/150?u=6",
                            CompanyName = "Stark Industries",
                            Email = "tony@stark.com",
                            IsActive = true,
                            Name = "Stark Industries"
                        },
                        new
                        {
                            Id = 7,
                            AvatarUrl = "https://i.pravatar.cc/150?u=7",
                            CompanyName = "Cyberdyne",
                            Email = "skynet@cyberdyne.com",
                            IsActive = true,
                            Name = "Cyberdyne Systems"
                        },
                        new
                        {
                            Id = 8,
                            AvatarUrl = "https://i.pravatar.cc/150?u=8",
                            CompanyName = "Massive Dynamic",
                            Email = "nina@massive.com",
                            IsActive = true,
                            Name = "Massive Dynamic"
                        },
                        new
                        {
                            Id = 9,
                            AvatarUrl = "https://i.pravatar.cc/150?u=9",
                            CompanyName = "Hooli XYZ",
                            Email = "gavin@hooli.com",
                            IsActive = false,
                            Name = "Hooli"
                        },
                        new
                        {
                            Id = 10,
                            AvatarUrl = "https://i.pravatar.cc/150?u=10",
                            CompanyName = "Pied Piper",
                            Email = "richard@piedpiper.com",
                            IsActive = true,
                            Name = "Pied Piper"
                        },
                        new
                        {
                            Id = 11,
                            AvatarUrl = "https://i.pravatar.cc/150?u=11",
                            CompanyName = "Wayne Enterprises",
                            Email = "bruce@wayne.com",
                            IsActive = true,
                            Name = "Wayne Enterprises"
                        },
                        new
                        {
                            Id = 12,
                            AvatarUrl = "https://i.pravatar.cc/150?u=12",
                            CompanyName = "Acme Corp",
                            Email = "roadrunner@acme.com",
                            IsActive = true,
                            Name = "Acme Corp"
                        },
                        new
                        {
                            Id = 13,
                            AvatarUrl = "https://i.pravatar.cc/150?u=13",
                            CompanyName = "Oscorp Industries",
                            Email = "norman@oscorp.com",
                            IsActive = true,
                            Name = "Oscorp"
                        },
                        new
                        {
                            Id = 14,
                            AvatarUrl = "https://i.pravatar.cc/150?u=14",
                            CompanyName = "Nakatomi",
                            Email = "takagi@nakatomi.com",
                            IsActive = true,
                            Name = "Nakatomi Trading"
                        },
                        new
                        {
                            Id = 15,
                            AvatarUrl = "https://i.pravatar.cc/150?u=15",
                            CompanyName = "Tyrell Corporation",
                            Email = "elden@tyrell.com",
                            IsActive = false,
                            Name = "Tyrell Corp"
                        });
                });

            modelBuilder.Entity("BillTrackPro.Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateIssued")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 12450.32m,
                            ClientId = 1,
                            DateIssued = new DateTime(2023, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-001",
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 3450.00m,
                            ClientId = 2,
                            DateIssued = new DateTime(2023, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-002",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 890.00m,
                            ClientId = 3,
                            DateIssued = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-003",
                            Status = "Overdue"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 2100.00m,
                            ClientId = 4,
                            DateIssued = new DateTime(2023, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-004",
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 5600.00m,
                            ClientId = 5,
                            DateIssued = new DateTime(2023, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-005",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 10420.00m,
                            ClientId = 6,
                            DateIssued = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-006",
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 1500.00m,
                            ClientId = 7,
                            DateIssued = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-007",
                            Status = "Overdue"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 3200.00m,
                            ClientId = 8,
                            DateIssued = new DateTime(2023, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-008",
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 750.00m,
                            ClientId = 1,
                            DateIssued = new DateTime(2023, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-009",
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 9800.00m,
                            ClientId = 2,
                            DateIssued = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-010",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 450.00m,
                            ClientId = 9,
                            DateIssued = new DateTime(2023, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-011",
                            Status = "Overdue"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 16700.00m,
                            ClientId = 10,
                            DateIssued = new DateTime(2023, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-012",
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 13,
                            Amount = 25000.00m,
                            ClientId = 11,
                            DateIssued = new DateTime(2023, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-013",
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 14,
                            Amount = 1200.00m,
                            ClientId = 12,
                            DateIssued = new DateTime(2023, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-014",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 15,
                            Amount = 3400.00m,
                            ClientId = 13,
                            DateIssued = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-015",
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 16,
                            Amount = 8900.00m,
                            ClientId = 14,
                            DateIssued = new DateTime(2023, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-016",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 17,
                            Amount = 450.00m,
                            ClientId = 15,
                            DateIssued = new DateTime(2023, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-017",
                            Status = "Overdue"
                        },
                        new
                        {
                            Id = 18,
                            Amount = 2100.00m,
                            ClientId = 1,
                            DateIssued = new DateTime(2023, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-018",
                            Status = "Paid"
                        },
                        new
                        {
                            Id = 19,
                            Amount = 300.00m,
                            ClientId = 3,
                            DateIssued = new DateTime(2023, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-019",
                            Status = "Overdue"
                        },
                        new
                        {
                            Id = 20,
                            Amount = 4600.00m,
                            ClientId = 5,
                            DateIssued = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InvoiceNumber = "INV-2024-020",
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("BillTrackPro.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("BillTrackPro.Domain.Entities.Client", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BillTrackPro.Domain.Entities.Client", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
